kind: Service
apiVersion: v1
metadata:
  name: "nodejs-example"
  annotations:
    description: Exposes and load balances the application pods
spec:
  ports:
  - name: web
    port: 8081
    targetPort: 8081
  selector:
    name: "nodejs-example"
